ci: create github test report

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -26,5 +26,10 @@ jobs:
         run: npm ci --ignore-scripts
       - name: Test (With Coverage)
         run: npm test -- --coverage
+      - uses: actions/upload-artifact@v2
+          if: success() || failure() # run this step even if previous step failed
+          with:
+            name: test-results
+            path: test/junit.xml
       - name: Upload coverage reports to Codecov
         uses: codecov/codecov-action@v3
