ci: fix ci

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -12,6 +12,17 @@ jobs:
           node-version: '18.x'
       - run: npm ci --ignore-scripts
       - run: npm run build
+  lint:
+    name: Lint
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: '18.x'
+      - run: npm ci --ignore-scripts
+      - run: npm run lint
+      - run: npm run format
   test:
     name: Test
     runs-on: ubuntu-latest
@@ -25,11 +36,11 @@ jobs:
       - name: Install dependencies
         run: npm ci --ignore-scripts
       - name: Test (With Coverage)
-        run: npm test -- --coverage
+        run: npm test:coverage
       - uses: actions/upload-artifact@v2
-          if: success() || failure() # run this step even if previous step failed
-          with:
-            name: test-results
-            path: test/junit.xml
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: test-results
+          path: test/junit.xml
       - name: Upload coverage reports to Codecov
         uses: codecov/codecov-action@v3
