build: update

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -28,6 +28,8 @@ jobs:
             - name: Install dependencies
               run: npm ci --ignore-scripts
 
+            - name: Build
+              run: npm run build
             - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
               run: npm audit signatures
             - name: Release
@@ -36,10 +38,9 @@ jobs:
                   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
               run: npx semantic-release
     no-release:
-      if: ${{ (github.event_name != 'pull_request') && (github.event.workflow_run.conclusion == 'failure') }}
-      name: No Release
-      runs-on: ubuntu-latest
-      steps:
-        - name: CI Failure
-          run: echo "CI Failure" && exit 1
-
+        if: ${{ (github.event_name != 'pull_request') && (github.event.workflow_run.conclusion == 'failure') }}
+        name: No Release
+        runs-on: ubuntu-latest
+        steps:
+            - name: CI Failure
+              run: echo "CI Failure" && exit 1
